apiVersion: v1
kind: Pod
metadata:
  name: selector
  labels:
    purpose: "selector-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx


# kubectl apply -f 01-node-selector.yaml

# If worker nodes are in 1a and 1b zone but the nodeselector is given as 1c then
# Pod will not create and it will be in Pending status

# kubectl delete -f 01-node-selector.yaml

# Errors in K8
# ==============
# ErrImagePull --> if node is not able to pull the image
# CrashLoopBackOff --> Container is unable to start
# Pending --> worker node not availalbe in that AZ, PVC is not bound to PV
# ContainerCreating --> PV, PVC

# You can use any of the following methods to choose where Kubernetes schedules specific Pods:

# nodeSelector field matching against node labels
# Affinity and anti-affinity
# nodeName field
# Pod topology spread constraints